new 6 спринт
ComradT/java-kanban pull request #9
Opened 2024-05-13 12:42 UTC by ComradT

2024-05-13 12:48 UTC, ComradT commented
Сделал new branch Sprint-6-solution

2024-05-14 08:50 UTC, Fleaman777 requested changes

2024-05-14 08:50 UTC, Fleaman777 commented on src/service/InMemoryHistoryManager.java
> +    private static class Node {
молодец, что этот класс сделал внутренним, отдельно его смысла нет создавать, так как он напрямую связан с менеджером истории,
но его объявление лучше перенести в конец класса InMemoryHistoryManager, так будет более верно с точки зрения джава код стайла

2024-05-14 08:50 UTC, Fleaman777 commented on test/service/InMemoryHistoryManagerTest.java
> +        assertEquals(historyManager.getHistory(), List.of(task1, task2));
у тебя вроде equals и hashcode переопределены в Task, и значит тест отработfет корректно,
но с equals всегда нужно быть внимательным, что бы он был переопределен

2024-05-14 08:50 UTC, Fleaman777 commented on test/service/InMemoryHistoryManagerTest.java
> +        Task task3 = createTask(3);
часть общей логики по созданию задач и заполнению историм можно было бы вынести в метод setUp

2024-05-14 08:50 UTC, Fleaman777 commented on test/service/InMemoryHistoryManagerTest.java
> +
согласно ТЗ еще нужно добавить тесты на менеджер задач, 
пункт:
- Покройте тестами ещё несколько функций менеджера задач, которые вы реализовали в предыдущих спринтах. Отдельно уделите внимание целостности данных:
...

2024-05-14 15:40 UTC, ComradT commented on src/service/InMemoryHistoryManager.java
> +    private static class Node {
Спасибо, сделал

2024-05-14 15:41 UTC, ComradT commented on test/service/InMemoryHistoryManagerTest.java
> +        assertEquals(historyManager.getHistory(), List.of(task1, task2));
Так точно, equals и hashcode переопределены в Task

2024-05-14 15:42 UTC, ComradT commented on test/service/InMemoryHistoryManagerTest.java
> +        Task task3 = createTask(3);
Создал метод setUp

2024-05-14 15:49 UTC, ComradT commented on test/service/InMemoryHistoryManagerTest.java
> +
есть тест сравнения по всем полям Task, Epic, SubTask, плюс добавил в него сравнение списка вновь созданного и добавленного в HistoryManager.

2024-05-15 14:12 UTC, Fleaman777 approved these changes

2024-05-15 14:12 UTC, Fleaman777 commented on test/service/InMemoryHistoryManagerTest.java
> +    private HistoryManager setUp(int id) {
можно этот  метод переименовать, или другой setUp 

Дефицита на названия методов нет)

2024-05-26 14:11 UTC, merged